Playwright equivalent of Cypress test for list of projects cards ✓
Noffica/QA-Automation-With-Profy.Dev pull request #12
Opened 2024-08-21 21:37 UTC by Noffica

includes re-installation of `husky`

2024-08-21 21:41 UTC, romanchukenator requested changes

2024-08-21 21:41 UTC, romanchukenator commented on tests/project-list.spec.ts
> +    */
Probably want to delete this

2024-08-21 21:41 UTC, romanchukenator commented on tests/project-list.spec.ts
> +  // );
Perhaps we don't need this?

2024-08-21 21:41 UTC, romanchukenator commented on tests/project-list.spec.ts
> +import projectsMockedResponseBody from "./fixtures/projects.json";
Small tiny 🌵 but it's a long name. `projectsMock` or `mockProjectsRes` or whatever. No need to change.

2024-08-24 00:44 UTC, Noffica commented on features/projects/components/project-card/project-card.tsx
Lines 2-6 inclusive were modified by linting.

2024-08-26 19:33 UTC, romanchukenator requested changes
Looks good, a couple requests.

Maybe change the PR commit something more imperative, like, Add Playwright tests for project cards.

Also, I think the husky issues plaguing you are probably due to some gitignore wackiness. But, if I look at your PR I'm not seeing anything husky related so I'd remove that comment.

Lets try removing the gitignore content, push the latest husky changes for one PR and then on a subsequent PR we'll add the gitignore content back.

2024-08-26 19:33 UTC, romanchukenator commented on features/projects/components/project-card/project-card.tsx
> +    <div className={styles.container} data-testID={name}>
Change to the id attribute, please. Names aren't necessarily unique.

2024-08-26 19:33 UTC, romanchukenator commented on tests/project-list.spec.ts
> +        // await expect(card).toContainText(mockedResponse.numEvents24h); //not drawn on the UI
These comments aren't exactly correct. If you look at the `project-card.tsx` code you'll see the block of text trying to access the issues and events:

```javascript
        <div className={styles.infoContainer}>
          <div className={styles.issues}>
            <div className={styles.issuesTitle}>Total issues</div>
            <div className={styles.issuesNumber}>{numIssues}</div>
          </div>
          <div className={styles.issues}>
            <div className={styles.issuesTitle}>Last 24h</div>
            <div className={styles.issuesNumber}>{numEvents24h}</div>
          </div>
          <div className={styles.status}>
            <Badge color={statusColors[status]}>{capitalize(status)}</Badge>
          </div>
        </div>
```

and if you look at the page you can see that the labels "Total issues" and "Last 24h" are there without their data.

It's going to be an interesting problem to figure out and we'll have a couple ways to address the bug fix.

...long story short: either change the comments to reflect the bug issue or just remove them.

2024-08-26 19:33 UTC, romanchukenator commented on features/projects/components/project-list/project-list.tsx
> +    <ul className={styles.list} data-testID={"project-cards-list"}>
There's no real technical issue with tagging this with a test attribute but since we're not making use of it in any of our tests I don't think there's much reason to add it.

2024-08-26 19:33 UTC, romanchukenator commented on features/projects/components/project-card/project-card.tsx
> +    <div className={styles.container} data-testID={name}>
Also, I'd pick either this file and html tag or the `li` item in the `project-list.tsx` to add the test attribute. I'm leaning more towards tagging the `project-card.tsx` file since what we're really trying to locate and test is the project card and not the `li`.

2024-08-26 19:33 UTC, romanchukenator commented on features/projects/components/project-list/project-list.tsx
> +        <li key={project.id} data-testID={project.id}>
I left a comment on the `project-card.tsx` file that applies here

2024-08-26 19:33 UTC, romanchukenator commented on tests/project-list.spec.ts
> +        .all();
I'm not sure this is really necessary. I think we're 

1. looking to test the number of cards on the page (useful-ish when testing, say, query limits or pagination)
2. looking to see that each card renders the proper data.

So, we need to total number of cards and then a way to grab each individual card, right?

```javascript
      const projectCards = page.locator("main ul").getByRole("listitem");

      await expect(projectCards).toHaveCount(3);
```

And then we get to take advantage of our test id tags with
```javascript
      for (const projectData of projectsMockedResponseBody.data) {
        const card = page.getByTestId(projectData.id);
...
      }

```

2024-08-27 07:58 UTC, romanchukenator approved these changes

2024-08-27 07:58 UTC, romanchukenator commented on features/projects/components/project-card/project-card.tsx
> +    <div className={styles.container} data-testID={project.id}>
🌵  There's like a weird warning/error react or the Playwright debugger is throwing at me about using a capitalized `ID`.

Playwright docs list the supported attributes: https://playwright.dev/docs/other-locators#id-data-testid-data-test-id-data-test-selectors

And while this works it's worth noting the warning, hence why it's a 🌵

2024-08-27 19:02 UTC, merged